# Copyright (c) OpenMMLab. All rights reserved.
from typing import Sequence

import torch
import torch.nn as nn
from mmcv.cnn import ConvModule
from mmengine.model import BaseModule
from torch import Tensor

from mmdet.registry import MODELS

from .cspnext import CSPNeXt
from .vmamba_official.vmamba import Backbone_VSSM


@MODELS.register_module()
class RTMDetMMVMambaBackbone(Backbone_VSSM):
    """VMamba wrapper that exposes RTMDet-style P3/P4/P5 outputs."""

    def __init__(self,
                 out_indices: Sequence[int] = (1, 2, 3),
                 norm_layer: str = 'ln',
                 **kwargs) -> None:
        kwargs.pop('init_cfg', None)
        super().__init__(out_indices=out_indices, norm_layer=norm_layer,
                         **kwargs)

    def init_weights(self) -> None:
        # Backbone_VSSM already loads pretrained weights in __init__.
        pass


@MODELS.register_module()
class RTMDetHybridVMambaBackbone(BaseModule):
    """Hybrid backbone: keep early CSPNeXt stages and replace late stages.

    P3 comes from the original CSPNeXt stage-2 output. P4/P5 are generated by
    feeding that P3 feature through the later VMamba stages. This keeps the
    engineering intent of "front CSP, back VMamba" while allowing separate
    pretrained weights for both branches.
    """

    def __init__(self,
                 csp_deepen_factor: float = 0.167,
                 csp_widen_factor: float = 0.375,
                 csp_expand_ratio: float = 0.5,
                 csp_channel_attention: bool = True,
                 csp_norm_cfg: dict = dict(type='SyncBN'),
                 csp_act_cfg: dict = dict(type='SiLU', inplace=True),
                 csp_init_cfg: dict | None = None,
                 vmamba_pretrained: str | None = None,
                 vmamba_depths: Sequence[int] = (2, 2, 9, 2),
                 vmamba_dims: Sequence[int] = (96, 192, 384, 768),
                 vmamba_drop_path_rate: float = 0.2,
                 ssm_d_state: int = 1,
                 ssm_ratio: float = 2.0,
                 ssm_dt_rank='auto',
                 ssm_act_layer: str = 'silu',
                 ssm_conv: int = 3,
                 ssm_conv_bias: bool = False,
                 ssm_drop_rate: float = 0.0,
                 ssm_init: str = 'v0',
                 forward_type: str = 'v05_noz',
                 mlp_ratio: float = 4.0,
                 mlp_act_layer: str = 'gelu',
                 mlp_drop_rate: float = 0.0,
                 gmlp: bool = False,
                 patch_norm: bool = True,
                 norm_layer: str = 'ln',
                 downsample_version: str = 'v3',
                 patchembed_version: str = 'v2',
                 init_cfg: dict | None = None) -> None:
        super().__init__(init_cfg=init_cfg)
        self.csp_backbone = CSPNeXt(
            arch='P5',
            deepen_factor=csp_deepen_factor,
            widen_factor=csp_widen_factor,
            out_indices=(2, ),
            expand_ratio=csp_expand_ratio,
            channel_attention=csp_channel_attention,
            norm_cfg=csp_norm_cfg,
            act_cfg=csp_act_cfg,
            init_cfg=csp_init_cfg)

        self.vmamba_backbone = Backbone_VSSM(
            out_indices=(2, 3),
            pretrained=vmamba_pretrained,
            depths=list(vmamba_depths),
            dims=list(vmamba_dims),
            drop_path_rate=vmamba_drop_path_rate,
            patch_size=4,
            in_chans=3,
            num_classes=1000,
            ssm_d_state=ssm_d_state,
            ssm_ratio=ssm_ratio,
            ssm_dt_rank=ssm_dt_rank,
            ssm_act_layer=ssm_act_layer,
            ssm_conv=ssm_conv,
            ssm_conv_bias=ssm_conv_bias,
            ssm_drop_rate=ssm_drop_rate,
            ssm_init=ssm_init,
            forward_type=forward_type,
            mlp_ratio=mlp_ratio,
            mlp_act_layer=mlp_act_layer,
            mlp_drop_rate=mlp_drop_rate,
            gmlp=gmlp,
            patch_norm=patch_norm,
            norm_layer=norm_layer,
            downsample_version=downsample_version,
            patchembed_version=patchembed_version)

        p3_channels = int(CSPNeXt.arch_settings['P5'][1][1] * csp_widen_factor)
        vmamba_stage1_dim = self._expand_vmamba_dims(vmamba_dims)[1]
        self.bridge = ConvModule(
            p3_channels,
            vmamba_stage1_dim,
            kernel_size=1,
            stride=1,
            padding=0,
            norm_cfg=csp_norm_cfg,
            act_cfg=csp_act_cfg)

    @staticmethod
    def _expand_vmamba_dims(dims: Sequence[int] | int) -> list[int]:
        if isinstance(dims, int):
            return [dims * (2 ** idx) for idx in range(4)]
        return list(dims)

    @staticmethod
    def _forward_vmamba_layer(layer, x: Tensor) -> tuple[Tensor, Tensor]:
        out = layer.blocks(x)
        next_x = layer.downsample(out)
        return out, next_x

    def _normalize_vmamba_output(self, output: Tensor, stage_idx: int) -> Tensor:
        norm_layer = getattr(self.vmamba_backbone, f'outnorm{stage_idx}')
        output = norm_layer(output)
        if not self.vmamba_backbone.channel_first:
            output = output.permute(0, 3, 1, 2)
        return output.contiguous()

    def forward(self, x: Tensor) -> tuple[Tensor, Tensor, Tensor]:
        p3 = self.csp_backbone(x)[0]

        vmamba_input = self.bridge(p3)
        if not self.vmamba_backbone.channel_first:
            vmamba_input = vmamba_input.permute(0, 2, 3, 1).contiguous()

        _, vmamba_x = self._forward_vmamba_layer(
            self.vmamba_backbone.layers[1], vmamba_input)
        p4_raw, vmamba_x = self._forward_vmamba_layer(
            self.vmamba_backbone.layers[2], vmamba_x)
        p5_raw, _ = self._forward_vmamba_layer(
            self.vmamba_backbone.layers[3], vmamba_x)

        p4 = self._normalize_vmamba_output(p4_raw, 2)
        p5 = self._normalize_vmamba_output(p5_raw, 3)
        return (p3, p4, p5)